
export const LOCALIZATION = {

  application_name: 'f-scheme-drawer',
  common: {
    close: 'Close',
    search: 'Search',
    type_in_to_search: 'Type in to Search...',
    cancel: 'Cancel',
    skip: 'Skip',
    create: 'Create',
    new_item: 'New',
    rename: 'Rename',
    confirm: 'Confirm',
    move: 'Move',
    move_confirm_message: 'Are you sure you want to move this?',
    overwrite: 'Overwrite',
    overwrite_confirm_message: '${0} already exists in directory ${1}',
    cut: 'Cut',
    copy: 'Copy',
    copy_confirm_message: 'Are you sure you want to copy specified files?',
    paste: 'Paste',
    delete: 'Delete',
    delete_confirm_message: 'Are you sure you want to delete this?',
    name: 'Name',
    comment: 'Comment',
    select_type: 'Select type...',
  },
  explorer_panel: {
    project: 'Project',
    hide_explorer_panel: 'Hide',
    hide_search: 'Hide Search',
    expand_all: 'Expand All',
    collapse_all: 'Collapse All',
    reset_search: 'Reset Search',
    show_options_menu: 'Options',
    show_excluded_files: 'Show Excluded Files',
    sort_by_type: 'Sort By Type',
    directories_always_on_top: 'Directories Always On Top',
    open_files_with_single_click: 'Open Files with Single Click',
    always_select_opened_file: 'Always Select Opened File',
    and_more_files: 'and ${0} more files',
  },
  'scratch-file': {
    name: 'Scratch File',
  },
}
